src/Entity/Dinosaur.php
<?php

namespace App\Entity;

use App\Enum\HealthStatus;
use App\Repository\DinosaurRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: DinosaurRepository::class)]
class Dinosaur
{
    #[ORM\Id, ORM\GeneratedValue, ORM\Column]
    private ?int $id = null;

    #[ORM\Column]
    private string $name;

    #[ORM\Column]
    private string $genus;

    #[ORM\Column]
    private int $length;

    #[ORM\Column]
    private string $enclosure;

    #[ORM\Column]
    private HealthStatus $health = HealthStatus::HEALTHY;

    public function __construct(string $name, string $genus = 'Unknown', int $length = 0, string $enclosure = 'Unknown')
    {
        $this->name = $name;
        $this->genus = $genus;
        $this->length = $length;
        $this->enclosure = $enclosure;
    }

    public function getId(): int
    {
        return $this->id;
    }

    public function getName(): string
    {
        return $this->name;
    }

    public function getGenus(): string
    {
        return $this->genus;
    }

    public function getLength(): int
    {
        return $this->length;
    }

    public function getEnclosure(): string
    {
        return $this->enclosure;
    }

    public function getSizeDescription(): string
    {
        if ($this->length >= 10) {
            return 'Large';
        }

        if ($this->length >= 5) {
            return 'Medium';
        }

        return 'Small';
    }

    public function isAcceptingVisitors(): bool
    {
        return $this->health !== HealthStatus::SICK;
    }

    public function setHealth(HealthStatus $health): void
    {
        $this->health = $health;
    }
}

src/Entity/LockDown.php
<?php

namespace App\Entity;

use App\Enum\LockDownStatus;
use App\Repository\LockDownRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: LockDownRepository::class)]
class LockDown
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column]
    private ?\DateTimeImmutable $createdAt = null;

    #[ORM\Column(nullable: true)]
    private ?\DateTimeImmutable $endedAt = null;

    #[ORM\Column(type: Types::STRING, enumType: LockDownStatus::class)]
    private ?LockDownStatus $status = LockDownStatus::ACTIVE;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $reason = null;

    public function __construct()
    {
        $this->createdAt = new \DateTimeImmutable();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->createdAt;
    }

    public function setCreatedAt(\DateTimeImmutable $createdAt): static
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    public function getEndedAt(): ?\DateTimeImmutable
    {
        return $this->endedAt;
    }

    public function getStatus(): LockDownStatus
    {
        return $this->status;
    }

    public function setStatus(LockDownStatus $status): static
    {
        $this->status = $status;
        if ($status === LockDownStatus::ENDED) {
            $this->endedAt = new \DateTimeImmutable();
        } else {
            $this->endedAt = null;
        }

        return $this;
    }

    public function getReason(): ?string
    {
        return $this->reason;
    }

    public function setReason(string $reason): static
    {
        $this->reason = $reason;

        return $this;
    }
}

src/Controller/MainController.php
<?php
declare(strict_types=1);

namespace App\Controller;

use App\Repository\DinosaurRepository;
use App\Repository\LockDownRepository;
use App\Service\GithubService;
use App\Service\LockDownHelper;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

final class MainController extends AbstractController
{
    #[Route(path: '/', name: 'app_homepage', methods: ['GET'])]
    public function index(
        DinosaurRepository $repository,
        GithubService $github,
        LockDownRepository $lockDownRepository,
    ): Response {
        $dinos = $repository->findAll();

        foreach ($dinos as $dino) {
            $dino->setHealth($github->getHealthReport($dino->getName()));
        }

        return $this->render('main/index.html.twig', [
            'dinos' => $dinos,
            'isLockDown' => $lockDownRepository->isInLockDown(),
        ]);
    }

    #[Route('/lockdown/end', name: 'app_lockdown_end', methods: ['POST'])]
    public function endLockDown(LockDownHelper $lockDownHelper, Request $request): Response
    {
        if (!$this->isCsrfTokenValid('end-lockdown', $request->request->get('_token'))) {
            throw $this->createAccessDeniedException('Invalid CSRF token');
        }

        $lockDownHelper->endCurrentLockDown();

        return $this->redirectToRoute('app_homepage');
    }
}

templates/base.html.twig
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <title>{% block title %}Welcome to Dinotopia!{% endblock %}</title>
        <link rel="stylesheet" href="{{ asset('styles/styles.css') }}">
        <!-- CSS only -->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
        <script src="https://kit.fontawesome.com/fab65cceab.js" crossorigin="anonymous"></script>
        <script type="module"> import 'https://cdn.jsdelivr.net/npm/@hotwired/turbo@7.3.0/+esm';</script>
        <link rel="icon" href="data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 128 128%22><text y=%221.2em%22 font-size=%2296%22>⚫️</text></svg>">
        {% block stylesheets %}
        {% endblock %}

        {% block javascripts %}
        {% endblock %}
    </head>
    <body>
    {% block body %}
    {% endblock %}
    </body>
</html>

templates/main/_lockDownAlert.html.twig
<div class="modal show d-block" tabindex="-1" role="dialog" id="myModal">
    <div class="modal-dialog" role="document">
        <div class="modal-content bg-danger text-white">
            <div class="modal-header">
                <h5 class="modal-title">
                    DINOSAUR ALERT
                    <svg xmlns="http://www.w3.org/2000/svg" height="1em" viewBox="0 0 512 512"><!--! Font Awesome Free 6.4.2 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license (Commercial License) Copyright 2023 Fonticons, Inc. --><path style="fill: white;" d="M256 32c14.2 0 27.3 7.5 34.5 19.8l216 368c7.3 12.4 7.3 27.7 .2 40.1S486.3 480 472 480H40c-14.3 0-27.6-7.7-34.7-20.1s-7-27.8 .2-40.1l216-368C228.7 39.5 241.8 32 256 32zm0 128c-13.3 0-24 10.7-24 24V296c0 13.3 10.7 24 24 24s24-10.7 24-24V184c0-13.3-10.7-24-24-24zm32 224a32 32 0 1 0 -64 0 32 32 0 1 0 64 0z"/></svg>
                </h5>
            </div>
            <div class="modal-body text-center">
                <p>Lockdown initiated! The dinosaurs are loose! I'm having a bad day!</p>
            </div>
            <div class="modal-footer">
                <form action="{{ path('app_lockdown_end') }}" method="POST">
                    <input type="hidden" name="_token" value="{{ csrf_token('end-lockdown') }}">
                    <button class="btn btn-warning" data-dismiss="modal">
                        End Lockdown
                    </button>
                </form>
            </div>
        </div>
    </div>
</div>
<div class="modal-backdrop show"></div>

templates/main/index.html.twig
{% extends 'base.html.twig' %}

{% block body %}

    {% if isLockDown %}
        {{ include('main/_lockDownAlert.html.twig') }}
    {% endif %}

    <div class="container volcano mt-4" style="flex-grow: 1;">
        <h1 class="mt-5">Dinotopia Status</h1>
        <div class="dino-stats-container mt-2 p-3">
            <table class="table table-striped">
                <thead>
                <tr>
                    <th>Name</th>
                    <th>Genus</th>
                    <th>Size</th>
                    <th>Enclosure</th>
                    <th>Accepting Visitors</th>
                </tr>
                </thead>
                <tbody>
                {% for dino in dinos %}
                    <tr>
                        <td>{{ dino.name }}</td>
                        <td>{{ dino.genus }}</td>
                        <td>{{ dino.sizeDescription }}</td>
                        <td>{{ dino.enclosure }}</td>
                        <td>{{ dino.acceptingVisitors ? 'Yes' : 'No' }}</td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
    <div class="container">
        <footer class="d-flex flex-wrap justify-content-between align-items-center py-3 my-4 border-top">
            <div class="col-md-4 d-flex align-items-center">
                <a href="https://github.com/SymfonyCasts/dino-park" target="_blank"
                   class="mb-3 me-2 mb-md-0 text-decoration-none lh-1 text-light">
                    <p><i>GenLab Secret Dino Repository</i></p>
                </a>
            </div>

            <div class="col-md-4 d-flex justify-content-center align-items-center">
                <a href="https://symfonycasts.com/" class="mb-3 me-2 mb-md-0 text-light text-decoration-none lh-1">
                    <p>With ❤️ from the gals and guys at SymfonyCasts</p>
                </a>
            </div>

            <ul class="nav col-md-4 justify-content-end list-unstyled d-flex">
                <li class="ms-3"><a class="text-light" href="https://github.com/SymfonyCasts"><i
                                class="fab fa-github"></i></a></li>
                <li class="ms-3"><a class="text-light" href="https://twitter.com/symfonycasts"><i
                                class="fab fa-twitter"></i></a></li>
                <li class="ms-3"><a class="text-light" href="https://www.facebook.com/SymfonyCasts/"><i
                                class="fab fa-facebook"></i></a></li>
            </ul>
        </footer>
    </div>

{% endblock %}